install-wasi-target:
    rustup target add wasm32-wasip2

build mode="debug": install-wasi-target 
    cargo build --target wasm32-wasip2 {{ if mode == "release" { "--release" } else { "" } }} 

build-auditable mode="debug": install-wasi-target 
    cargo auditable build --target wasm32-wasip2 {{ if mode == "release" { "--release" } else { "" } }}