package component:fetch-rs;

/// An example world for the component to target.
world fetch {
    /// Fetch data from a URL and return the response body as a String
    export fetch: func(url: string) -> result<string, string>;
}
